name: Repo Sync

on:
  schedule: 
  - cron: "*/15 * * * *"
  push:
    tags: ["v*.*"]
  release:
    types:
      - created
      - published
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch - main
      with:
        source_repo: z-shell/zinit
        source_branch: main
        destination_branch: sync
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request - main
      with:
        source_branch: sync
        destination_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
