name: Repo Sync

on:
  schedule: 
  - cron: "*/15 * * * *"
  push:
    tags: ["v*.*"]
  release:
    types:
      - created
      - published
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Repo Sync
      uses: repo-sync/github-sync@v2.3.0
      with:
        source_repo: z-shell/zinit
        source_branch: main
        destination_branch: sync-main 
        github_token: ${{ secrets.GITHUB_TOKEN }}
