name: Zinit Sync

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-sync
        run: | 
          sudo apt-get update
          sudo apt-get install git -y

      - name: Clone origin
        run: |
          export REPO_NAME=zinit.git
          export ORIGIN_URL=git@github.com:ss-o/$REPO_NAME
          export REPO1_URL=git@github.com:z-shell/$REPO_NAME
          
          git remote add --mirror=fetch repo1 $REPO1_URL
          git fetch origin --tags
          git fetch repo1 --tags
          git push origin --all
          git push origin --tags
          git push repo1 --all
          git push repo1 --tags
